import '@/styles/globals.css'
import {Montserrat} from "next/font/google"
import Head from 'next/head'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import { AnimatePresence } from 'framer-motion'
import { useRouter } from 'next/router'

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
})

export default function App({ Component, pageProps }) {
  const router = useRouter()
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <title>Fadila Portfolio Website</title>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>

        <meta name="title" content="Fadila Portfolio Website" />
<meta name="description" content="Turning Vision Into Reality With Code And Design || As a skilled full-stack developer, AI Engineer, PHP Laravel and Javascript based Web Developer" />

// Open Graph / Facebook
<meta property="og:type" content="website" />
<meta property="og:url" content="https://fadila.tech/" />
<meta property="og:title" content="Fadila Portfolio Website" />
<meta property="og:description" content="Turning Vision Into Reality With Code And Design || As a skilled full-stack developer, AI Engineer, PHP Laravel and Javascript based Web Developer" />
<meta property="og:image" content="/images/meta-tags.png" />

{/* <!-- Twitter --> */}
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content="https://fadila.tech/" />
<meta property="twitter:title" content="Fadila Portfolio Website" />
<meta property="twitter:description" content="Turning Vision Into Reality With Code And Design || As a skilled full-stack developer, AI Engineer, PHP Laravel and Javascript based Web Developer" />
<meta property="twitter:image" content="/images/meta-tags.png" />

      </Head>
      <main className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}>
        <NavBar/>
        <AnimatePresence mode="wait">
        <Component key={router.asPath} {...pageProps} />
        </AnimatePresence>
        <Footer />
      </main>
    </>
  )
  
  
}
